// Code generated by goctl. DO NOT EDIT.
package types

type ListFileRequest struct {
	Path string `form:"path,optional"`
}

type DownloadRequest struct {
	File string `form:"file"`
}

type UploadRequest struct {
	Path string `form:"path"`
	UID  int    `form:"uid,optional"`
	GID  int    `form:"gid,optional"`
}

type Response struct {
	Code    int64       `json:"code"`
	Message string      `json:"message,omitempty"`
	Data    interface{} `json:"data,omitempty"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type ChpasswdReq struct {
	Username    string `json:"username"`
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type AddUserReq struct {
	Username string `json:"username"`
	Role     string `json:"role"`
}

type CallbackReq struct {
	Name string `path:"name"`
	Code string `form:"code"`
}

type GenereateTokenReq struct {
	UserId        int   `json:"user_id"`
	ExpireSeconds int64 `json:"expire_seconds"`
}

type DataByIdReq struct {
	Tablename string `path:"tablename"`
	Id        string `path:"id"`
}

type ListBucketRequest struct {
	Name string `form:"name"`
}

type ListObjectRequest struct {
	Name string `form:"name"`
	Path string `form:"path"`
}

type CreateBucketRequest struct {
	Name          string `form:"name"`
	BucketName    string `json:"bucket_name"`
	Versioning    bool   `json:"versioning,optional"`
	ObjectLocking bool   `json:"object_locking,optional"`
}
